version: '2'

services:
  redis:
    restart: always
    image: harbor.ctproject5.com/basic/redis:latest
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: harbor.ctproject5.com/basic/postgresql:9.6
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: harbor.ctproject5.com/basic/gitlab:8.15.3
    depends_on:
    - redis
    - postgresql
    ports:
    - "80:80"
    - "10022:22"
    - "8443:443"
    volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data:Z
    environment:
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Asia/Kolkata
    - GITLAB_TIMEZONE=Kolkata

    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=172.16.10.133
    - GITLAB_PORT=80
    - GITLAB_SSH_PORT=10022
     
    - GITLAB_SECRETS_DB_KEY_BASE=FpKcgFWvPbMjdHCrRWhPPgsKCsRzgsWNhbMLgrKfKcjrvPfqXh373XzmPkdzVrTh
    - GITLAB_SECRETS_SECRET_KEY_BASE=3Kjqzwq34fgKbNPLj3FtXLgRcKdXhkzHMzppWkhpX7j9pWpWrCrdFrxz47JngTqK
    - GITLAB_SECRETS_OTP_KEY_BASE=krm3TLxMkMW9XsFWVHgnXhxmcJPTjPmqmfgWgTcxJrntdwfdKFgXjWrVdfTCHVX9
    - GITLAB_ROOT_PASSWORD=gitlab123456
    - GITLAB_ROOT_EMAIL=cwd_test1@163.com

    - GITLAB_EMAIL=cwd_test1@163.com
    - GITLAB_EMAIL_REPLY_TO=cwd_test1@163.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=cwd_test1@163.com

    - GITLAB_BACKUP_SCHEDULE=weekly
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=163.com
    - SMTP_HOST=smtp.163.com
    - SMTP_PORT=25
    - SMTP_USER=cwd_test1@163.com
    - SMTP_PASS=zxcv5678
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
